version: '3'
services:
  web:
    build: .
    command: "java -Xmx1g -Djetbrains.youtrack.disableBrowser=true -jar youtrack-2017.4.38030.jar run"
    ports:
      - '8180:8080'
  health:
    image: "alpine"
    command: "top"