version: "3.3"
services:
  teamcity-server:
    image: jetbrains/teamcity-server:2018.1.1
    ports:
    - '8111:8111'
    volumes:
    - ~/.ci/teamcity_server/datadir:/data/teamcity_server/datadir
    - ~/.ci/teamcity_server/logs:/opt/teamcity/logs
    links:
    - postgres:postgres
  teamcity-agent:
    image: jetbrains/teamcity-agent:2018.1.1
    environment:
      SERVER_URL: 'teamcity-server:8111'
      DOCKER_IN_DOCKER: 'start'
    privileged: true
    links:
    - teamcity-server:teamcity-server
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/.ci/teamcity-agent/conf:/data/teamcity_agent/conf
    - ~/.ci/opt/buildagent/work:/opt/buildagent/work
    - ~/.ci/opt/buildagent/temp:/opt/buildagent/temp
    - ~/.ci/opt/buildagent/tools:/opt/buildagent/tools
    - ~/.ci/opt/buildagent/plugins:/opt/buildagent/plugins
    - ~/.ci/opt/buildagent/system:/opt/buildagent/system
  youtrack:
    image: jetbrains/youtrack:2018.2.44329
    ports:
    - '8080:8080'
    volumes:
    - ~/.ci/youtrack/data:/opt/youtrack/data
    - ~/.ci/youtrack/conf:/opt/youtrack/conf
    - ~/.ci/youtrack/logs:/opt/youtrack/logs
    - ~/.ci/youtrack/backups:/opt/youtrack/backups
    links:
    - postgres:postgres
  splunk:
    image: splunk/splunk:7.1.2
    environment:
      SPLUNK_START_ARGS: '--accept-license --seed-passwd 12345678'
    ports:
    - '8000:8000'
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
    - '8001:80'
    - '2003-2004:2003-2004'
    - '2023-2024:2023-2024'
    - '8125:8125/udp'
    - '8126:8126'
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'vsoshyn'
      POSTGRES_PASSWORD: '12345678'
    ports:
      - 5432:5432
  portainer:
    image: portainer/portainer
    ports:
    - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
volumes:
  portainer_data: