version: "3.3"
services:
  teamcity_server:
    image: jetbrains/teamcity-server:2018.1.1
    ports:
    - '8111:8111'
    volumes:
    - teamcity_server_data:/data/teamcity_server/datadir
    - teamcity_server_opt:/opt/teamcity/logs
    links:
    - postgres:postgres
  teamcity_agent:
    build:
      context: ./
      dockerfile: ./docker-teamcity-agent
    environment:
      SERVER_URL: 'teamcity_server:8111'
      DOCKER_IN_DOCKER: 'start'
    privileged: true
    links:
    - teamcity_server:teamcity_server
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - teamcity_agent_data:/data/teamcity_agent/conf
    - teamcity_agent_opt:/opt/buildagent
  youtrack:
    image: jetbrains/youtrack:2018.2.44329
    ports:
    - '8080:8080'
    volumes:
    - youtrack_opt:/opt/youtrack
    links:
    - postgres:postgres
  splunk:
    image: splunk/splunk:7.1.2
    environment:
      SPLUNK_START_ARGS: '--accept-license --seed-passwd 12345678'
    ports:
    - '8000:8000'
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
    - '8001:80'
    - '2003-2004:2003-2004'
    - '2023-2024:2023-2024'
    - '8125:8125/udp'
    - '8126:8126'
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'vsoshyn'
      POSTGRES_PASSWORD: '12345678'
    ports:
    - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data
  portainer:
    image: portainer/portainer
    ports:
    - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
volumes:
  teamcity_server_opt:
  teamcity_server_data:
  teamcity_agent_opt:
  teamcity_agent_data:
  youtrack_opt:
  postgres_data:
  portainer_data:
