version: "3.3"
services:
  teamcity_server:
    image: jetbrains/teamcity-server:2018.1.1
    ports:
    - '8111:8111'
    volumes:
    - teamcity_server_data:/data/teamcity_server/datadir
  teamcity_agent:
    build:
      context: ./
      dockerfile: ./docker-teamcity-agent
    environment:
      SERVER_URL: 'teamcity-server:8111'
      DOCKER_IN_DOCKER: 'start'
    privileged: true
    links:
    - teamcity_server:teamcity-server
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - teamcity_agent_data:/data/teamcity_agent/conf
    - teamcity_agent_tools:/opt/buildagent/tools
    - teamcity_agent_plugins:/opt/buildagent/plugins
    - teamcity_agent_system:/opt/buildagent/system
  youtrack:
    image: jetbrains/youtrack:2018.2.44329
    ports:
    - '8080:8080'
    volumes:
    - youtrack_data:/opt/youtrack/data
    - youtrack_conf:/opt/youtrack/conf
  splunk:
    image: splunk/splunk:7.1.2
    environment:
      SPLUNK_START_ARGS: '--accept-license --seed-passwd 12345678'
    ports:
    - '8000:8000'
    volumes:
    - splunk_opt:/opt/splunk
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
    - '8001:80'
    - '2003-2004:2003-2004'
    - '2023-2024:2023-2024'
    - '8125:8125/udp'
    - '8126:8126'
  postgres:
    build:
      context: ./
      dockerfile: ./docker-postgres
    environment:
      POSTGRES_USER: 'vsoshyn'
      POSTGRES_PASSWORD: '12345678'
    ports:
    - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data
  swagger:
    image: swaggerapi/swagger-ui
    ports:
    - 3003:8080
    environment:
      API_URL: http://${HOSTNAME}:3002/swagger.json
volumes:
  teamcity_server_data:
  teamcity_agent_data:
  teamcity_agent_tools:
  teamcity_agent_plugins:
  teamcity_agent_system:
  youtrack_data:
  youtrack_conf:
  postgres_data:
  splunk_opt:
