CREATE USER teamcity ENCRYPTED PASSWORD '12345678';
CREATE DATABASE teamcity;
GRANT ALL PRIVILEGES ON DATABASE teamcity TO teamcity;

-- CREATE USER home ENCRYPTED PASSWORD '12345678';
-- CREATE DATABASE home;
-- GRANT ALL PRIVILEGES ON DATABASE home TO home;
--
-- CREATE SCHEMA home;
-- GRANT ALL PRIVILEGES ON SCHEMA home TO home;