CREATE TABLE ITEM
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  NAME VARCHAR2(64) NOT NULL,
  DESCRIPTION VARCHAR2(128),
  LIFECYCLE NUMBER DEFAULT 0,
  MAINTENANCE_DATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_ITEM START WITH 1 INCREMENT BY 10;