CREATE TABLE INFO (
  ID NUMBER(*) CONSTRAINT PK_03 PRIMARY KEY NOT NULL,
  VALUE VARCHAR2(16) NOT NULL UNIQUE
);

CREATE TABLE ITEM_INFO
(
  ITEM NUMBER(*) NOT NULL CONSTRAINT FK_04 REFERENCES ITEM (ID),
  INFO NUMBER(*) NOT NULL CONSTRAINT FK_05 REFERENCES INFO (ID)
);
