INSERT INTO INFO (ID, VALUE) VALUES (2, 'info');
INSERT INTO INFO (ID, VALUE) VALUES (3, 'detail');
INSERT INTO INFO (ID, VALUE) VALUES (4, 'money');
INSERT INTO INFO (ID, VALUE) VALUES (5, 'phone');
INSERT INTO INFO (ID, VALUE) VALUES (6, 'cart');