ALTER TABLE ITEM_INFO DROP CONSTRAINT FK_IN_INFO_ID;
ALTER TABLE ITEM_INFO MODIFY INFO VARCHAR2(16);
ALTER TABLE ITEM_INFO ADD CONSTRAINT CH_II_I CHECK (INFO IN (
  'PHOTO',
  'INFO',
  'DETAIL',
  'MONEY',
  'PHONE',
  'CART'
));
DROP TABLE INFO PURGE;