ALTER TABLE ITEM_INFO DROP CONSTRAINT FK_05;
ALTER TABLE ITEM_INFO MODIFY INFO VARCHAR2(16);
ALTER TABLE ITEM_INFO ADD CONSTRAINT CH_01 CHECK (INFO IN (
  'PHOTO',
  'INFO',
  'DETAIL',
  'MONEY',
  'PHONE',
  'CART'
));
DROP TABLE INFO PURGE;