CREATE TABLE ITEM_ADVANCED (
  ITEM NUMBER(*) NOT NULL UNIQUE,
  IMAGE BLOB,
  PARENT NUMBER(*),
  SPECIALIST_COMPANY VARCHAR2(32),
  SPECIALIST_EMAIL VARCHAR2(32),
  SPECIALIST_PHONE NUMBER(10),
  SPECIALIST_COST NUMBER(10) CHECK (SPECIALIST_COST >= 0),
  FOREIGN KEY (ITEM) REFERENCES ITEM(ID),
  FOREIGN KEY (PARENT) REFERENCES ITEM_ADVANCED(ITEM)
);

CREATE TABLE ITEM_ADVANCED_ADDIT_DETAIL (
  ITEM_ADVANCED NUMBER(*) NOT NULL,
  NAME VARCHAR2(32),
  DESCRIPTION VARCHAR2(128),
  COST NUMBER(10) CHECK (COST >= 0),
  FOREIGN KEY (ITEM_ADVANCED) REFERENCES ITEM_ADVANCED(ITEM)
);