CREATE SEQUENCE SEQ_ADD_DETAIL START WITH 1 INCREMENT BY 1;
ALTER TABLE ITEM_ADVANCED_ADDIT_DETAIL ADD (
  ID NUMBER(*)
);

UPDATE ITEM_ADVANCED_ADDIT_DETAIL SET ID = SEQ_ADD_DETAIL.nextval;
COMMIT;

ALTER TABLE ITEM_ADVANCED_ADDIT_DETAIL ADD PRIMARY KEY (ID);

DROP SEQUENCE SEQ_ADD_DETAIL;
CREATE SEQUENCE SEQ_ADD_DETAIL START WITH 1 INCREMENT BY 10;
SELECT SEQ_ADD_DETAIL.nextval FROM dual;
SELECT SEQ_ADD_DETAIL.nextval FROM dual;