CREATE TABLE DELTA
(
  ID NUMBER PRIMARY KEY NOT NULL,
  SCRIPT_NAME VARCHAR2(64) NOT NULL,
  TS DATE NOT NULL,
  STATUS VARCHAR2(16) NOT NULL,
  FAILURE CLOB,
  DIGEST CLOB
);

CREATE SEQUENCE SEQ_DELTA;