CREATE TABLE DELTA
(
  SCRIPT_NAME VARCHAR2(64) PRIMARY KEY NOT NULL,
  TYPE VARCHAR2(16) NOT NULL,
  TS DATE NOT NULL,
  STATUS VARCHAR2(16) NOT NULL,
  FAILURE CLOB,
  DIGEST CLOB,
  CONSTRAINT CH_DA_TE CHECK (TYPE IN ('DML', 'DDL')),
  CONSTRAINT U_DA_S_T UNIQUE (SCRIPT_NAME, TYPE)
);