CREATE TABLE INFO (
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  VALUE VARCHAR2(16) NOT NULL UNIQUE
);

CREATE TABLE ITEM_INFO
(
  ITEM NUMBER(*) NOT NULL CONSTRAINT FK_IN_ITEM_ID REFERENCES ITEM (ID),
  INFO NUMBER(*) NOT NULL CONSTRAINT FK_IN_INFO_ID REFERENCES INFO (ID)
);
